name: Build and Push Docker Image

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mikecovlee/moe_peft:${{ github.event.release.tag_name }}
    - name: Push to the Docker Hub
      run: docker push mikecovlee/moe_peft:${{ github.event.release.tag_name }}
